sudo: required
services:
  - docker

before_install:
  - docker build -t coryaramirez/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run coryaramirez/react-test npm test -- --coverage

after_success:
  - docker build -t coryaramirez/multi-client ./client
  - docker build -t coryaramirez/multi-nginx ./nginx
  - docker build -t coryaramirez/multi-server ./server
  - docker build -t coryaramirez/multi-worker ./worker
  # Log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push coryaramirez/multi-client
  - docker push coryaramirez/multi-nginx
  - docker push coryaramirez/multi-server
  - docker push coryaramirez/multi-worker
